<definitions 
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdp="http://schemas.xmlsoap.org/ws/2006/02/devprof"
    xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
    xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
    xmlns:wprt="http://schemas.microsoft.com/windows/2006/08/wdp/print"
    xmlns:wprt12="http://schemas.microsoft.com/windows/2012/10/wdp/printV12"
    targetNamespace="http://schemas.microsoft.com/windows/2012/10/wdp/printV12"
    name="WSDPrinterService">
  <types>
    <!-- <xs:schema targetNamespace="http://schemas.microsoft.com/windows/2012/10/wdp/printV12">
      <xs:include schemaLocation="WDPPrintV12.xsd"/>
    </xs:schema> -->

  </types>
  <message name="PrinterElementsChangeEventMsg">
    <part name="body" element="wprt:PrinterElementsChangeEvent"/>
  </message>
  <portType name="PrinterServiceType">
    <operation name="PrinterElementsChangeEvent">
      <intput message="wprt:PrinterElementsChangeEventMsg"
              wsa:Action="http://schemas.microsoft.com/windows/2006/08/wdp/print/PrinterElementsChangeEvent" />
    </operation>
  </portType>
  <binding name="PrinterServiceBinding" type="wprt:PrinterServiceType">
    <wsoap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsp:PolicyReference URI="#ServicePolicy" />
    <operation name="PrinterElementsChangeEvent">
      <wsoap12:operation
          soapAction="http://schemas.microsoft.com/windows/2006/08/wdp/print/PrinterElementsChangeEvent"
          soapActionRequired="true" />
      <input>
          <wsoap12:body use="literal" />
      </input>
    </operation>
  </binding>
  <service name="PrinterService">
    <port name="PrinterPort" binding="wprt:PrinterServiceBinding">
      <wsoap12:address location="http://localhost/PrinterService/"/>
    </port>
  </service>
</definitions>
